theme: jekyll-theme-minimal

title: [Shubham Bishnoi]
logo: /stuff/photo.png
description: [C, C++, R, Tableau, Python, SQL, Spark, PySpark, Hive, Oozie, PuTTy, MATLAB, QGIS, VBA, JIRA, SharePoint, Latex, Photoshop, Confluence]